import type { ThemeId } from '@jam/protocol';
import { alpha, ensureContrast, mix } from './color';
import type { AnsiRole, Scheme, SyntaxRole, ThemeDefinition } from './themes';

/**
 * Editor-style themes: dark and light variants of palettes people already
 * know from their editors and tools. Each is written as a handful of anchor
 * colours — canvas, sidebar, text, accent, status, a syntax palette and six
 * ANSI colours — and `editorTheme` derives every other role the same way, so
 * the family stays consistent and cheap to extend.
 *
 * Palettes follow each source's public colour system. Where a published
 * colour would fall below JAM's contrast floors on its own canvas (tested in
 * resolve.test.ts), it is nudged just far enough to pass; these are JAM's
 * interpretations, not official ports. Proof is JAM's own sage-and-paper
 * palette. Surfaces are opaque by default: these themes are solid, and pane
 * opacity can still let a wallpaper through.
 */

type Syntax = Pick<
  Record<SyntaxRole, string>,
  'keyword' | 'string' | 'number' | 'function' | 'type' | 'comment'
> &
  Partial<Record<SyntaxRole, string>>;

interface Anchors {
  id: ThemeId;
  name: string;
  family: string;
  scheme: Scheme;
  note?: string;
  /** Main pane / editor canvas. */
  canvas: string;
  sidebar: string;
  raised?: string;
  text: string;
  muted?: string;
  accent: string;
  accentSecondary?: string;
  success: string;
  warning: string;
  danger: string;
  syntax: Syntax;
  ansi: Pick<Record<AnsiRole, string>, 'red' | 'green' | 'yellow' | 'blue' | 'magenta' | 'cyan'>;
}

const codexStops: [string, string, string] = ['#b1a7ff', '#7a9dff', '#3941ff'];

export function editorTheme(a: Anchors): ThemeDefinition {
  const dark = a.scheme === 'dark';
  const step = (amount: number) => mix(a.text, a.canvas, amount);
  // Every readable role meets JAM's floors on this theme's own canvas.
  const read = (colour: string, ratio = 4.5) => ensureContrast(colour, a.canvas, ratio);
  const text = {
    strong: mix(a.text, dark ? '#ffffff' : '#000000', 0.35),
    primary: a.text,
    body: read(step(0.06), 7),
    secondary: read(step(0.2)),
    muted: read(a.muted ?? step(0.34)),
    subtle: read(step(0.46), 3.5),
    faint: step(0.6),
    ghost: step(0.72),
  };
  const accent = ensureContrast(a.accent, a.canvas, 3);
  const accentText = read(accent);
  const terminalGround = mix(a.canvas, a.sidebar, 0.35);
  const bright = (colour: string) => mix(colour, text.strong, dark ? 0.38 : 0.25);
  const console = Object.fromEntries(
    Object.entries(a.ansi).map(([role, colour]) => [
      role,
      ensureContrast(colour, terminalGround, 3),
    ]),
  ) as Anchors['ansi'];
  const ansi: Record<AnsiRole, string> = {
    black: dark ? text.ghost : text.strong,
    white: dark ? text.secondary : text.faint,
    'bright-black': text.subtle,
    'bright-white': dark ? text.strong : text.muted,
    ...console,
    'bright-red': bright(a.ansi.red),
    'bright-green': bright(a.ansi.green),
    'bright-yellow': bright(a.ansi.yellow),
    'bright-blue': bright(a.ansi.blue),
    'bright-magenta': bright(a.ansi.magenta),
    'bright-cyan': bright(a.ansi.cyan),
  };
  const s = Object.fromEntries(
    Object.entries(a.syntax).map(([role, colour]) => [
      role,
      read(colour, role === 'comment' || role === 'punctuation' ? 3.5 : 4.5),
    ]),
  ) as Syntax;
  const status = { success: read(a.success), warning: read(a.warning), danger: read(a.danger) };
  return {
    id: a.id,
    name: a.name,
    family: a.family,
    note: a.note ?? '',
    scheme: a.scheme,
    base: dark ? mix(a.sidebar, '#000000', 0.25) : mix(a.sidebar, '#000000', 0.05),
    surfaces: {
      sidebar: [a.sidebar, 100],
      pane: [a.canvas, 100],
      paneMuted: [mix(a.canvas, a.sidebar, 0.5), 100],
      terminal: [terminalGround, 100],
    },
    raised: a.raised ?? (dark ? mix(a.canvas, a.text, 0.06) : mix(a.canvas, '#ffffff', 0.7)),
    overlay: a.raised ?? (dark ? mix(a.canvas, a.text, 0.05) : mix(a.canvas, '#ffffff', 0.7)),
    scrim: dark ? 'rgb(0 0 0 / 60%)' : 'rgb(20 20 28 / 24%)',
    browserWell: alpha(a.text, dark ? 3 : 4),
    badgeRing: a.canvas,
    tint: a.text,
    fills: dark ? [3.5, 6, 9] : [4, 6.5, 10],
    borders: dark ? [7, 10, 15] : [8, 12, 17],
    text,
    accent,
    accentSecondary: a.accentSecondary ?? accent,
    accentRoles: { strong: accentText },
    status: { ...status, soft: [11, 12, 10] },
    diff: {
      addText: read(mix(status.success, a.text, 0.3)),
      delText: read(mix(status.danger, a.text, 0.3)),
      addGutter: mix(status.success, a.canvas, 0.45),
      delGutter: mix(status.danger, a.canvas, 0.45),
    },
    provider: {
      claude: dark ? '#d48f74' : '#bd6444',
      codex: step(0.18),
      violet: console.magenta,
      codexStops,
    },
    glow: 'none',
    syntax: {
      variable: text.body,
      definition: text.strong,
      property: s.property ?? text.secondary,
      operator: s.operator ?? text.secondary,
      punctuation: s.punctuation ?? text.muted,
      tag: s.tag ?? s.keyword,
      attribute: s.attribute ?? s.type,
      meta: s.meta ?? s.type,
      heading: text.strong,
      link: accentText,
      code: s.code ?? s.string,
      quote: text.muted,
      marker: accentText,
      ...s,
    },
    ansi,
    terminal: { foreground: text.body, cursor: text.strong },
  };
}

const THEME_ANCHORS: Anchors[] = [
  {
    id: 'claude-dark',
    name: 'Claude Dark',
    family: 'Claude',
    scheme: 'dark',
    canvas: '#262624',
    sidebar: '#1f1e1d',
    raised: '#30302e',
    text: '#e5e3da',
    accent: '#d97757',
    accentSecondary: '#e0a080',
    success: '#8fbf7a',
    warning: '#e0b050',
    danger: '#e5736b',
    syntax: {
      keyword: '#e38b6b',
      string: '#a3c585',
      number: '#d9b46c',
      function: '#94b8e8',
      type: '#7cc4b4',
      comment: '#8e8b82',
      attribute: '#d9b46c',
    },
    ansi: {
      red: '#e5736b',
      green: '#8fbf7a',
      yellow: '#e0b050',
      blue: '#86aee6',
      magenta: '#c49be0',
      cyan: '#72c2b8',
    },
  },
  {
    id: 'claude-light',
    name: 'Claude Light',
    family: 'Claude',
    scheme: 'light',
    canvas: '#faf9f5',
    sidebar: '#f3f1ea',
    raised: '#ffffff',
    text: '#2f2d27',
    accent: '#c15f3c',
    success: '#3f7d3a',
    warning: '#94600f',
    danger: '#b8412e',
    syntax: {
      keyword: '#b4532f',
      string: '#5a7a2c',
      number: '#8a650e',
      function: '#3f5fa8',
      type: '#2c7466',
      comment: '#7f7c73',
      attribute: '#8a650e',
    },
    ansi: {
      red: '#b8412e',
      green: '#3f7d3a',
      yellow: '#8a650e',
      blue: '#3f5fa8',
      magenta: '#8a4fa8',
      cyan: '#2c7466',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    family: 'GitHub',
    scheme: 'dark',
    canvas: '#0d1117',
    sidebar: '#010409',
    raised: '#161b22',
    text: '#e6edf3',
    muted: '#8d96a0',
    accent: '#4493f8',
    success: '#3fb950',
    warning: '#d29922',
    danger: '#f85149',
    syntax: {
      keyword: '#ff7b72',
      string: '#a5d6ff',
      number: '#79c0ff',
      function: '#d2a8ff',
      type: '#ffa657',
      comment: '#8b949e',
      property: '#79c0ff',
      operator: '#ff7b72',
      tag: '#7ee787',
      attribute: '#79c0ff',
    },
    ansi: {
      red: '#ff7b72',
      green: '#3fb950',
      yellow: '#d29922',
      blue: '#58a6ff',
      magenta: '#bc8cff',
      cyan: '#39c5cf',
    },
  },
  {
    id: 'github-dark-dimmed',
    name: 'GitHub Dark Dimmed',
    family: 'GitHub',
    scheme: 'dark',
    note: 'dimmed',
    canvas: '#22272e',
    sidebar: '#1c2128',
    raised: '#2d333b',
    text: '#adbac7',
    accent: '#539bf5',
    success: '#57ab5a',
    warning: '#c69026',
    danger: '#e5534b',
    syntax: {
      keyword: '#f47067',
      string: '#96d0ff',
      number: '#6cb6ff',
      function: '#dcbdfb',
      type: '#f69d50',
      comment: '#768390',
      property: '#6cb6ff',
      operator: '#f47067',
      tag: '#8ddb8c',
      attribute: '#6cb6ff',
    },
    ansi: {
      red: '#f47067',
      green: '#57ab5a',
      yellow: '#c69026',
      blue: '#539bf5',
      magenta: '#b083f0',
      cyan: '#39c5cf',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    family: 'GitHub',
    scheme: 'light',
    canvas: '#ffffff',
    sidebar: '#f6f8fa',
    raised: '#ffffff',
    text: '#1f2328',
    muted: '#59636e',
    accent: '#0969da',
    success: '#1a7f37',
    warning: '#9a6700',
    danger: '#d1242f',
    syntax: {
      keyword: '#cf222e',
      string: '#0a3069',
      number: '#0550ae',
      function: '#8250df',
      type: '#953800',
      comment: '#59636e',
      property: '#0550ae',
      operator: '#cf222e',
      tag: '#116329',
      attribute: '#0550ae',
    },
    ansi: {
      red: '#cf222e',
      green: '#116329',
      yellow: '#7d4e00',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
    },
  },
  {
    id: 'pierre-dark',
    name: 'Pierre Dark',
    family: 'Pierre',
    scheme: 'dark',
    canvas: '#0a0a0a',
    sidebar: '#171717',
    raised: '#1c1c1c',
    text: '#fafafa',
    accent: '#009fff',
    success: '#0dbe4e',
    warning: '#ffca00',
    danger: '#ff2e3f',
    syntax: {
      keyword: '#ff678d',
      string: '#5ecc71',
      number: '#68cdf2',
      function: '#9d6afb',
      type: '#d568ea',
      comment: '#737373',
      variable: '#ffa359',
      property: '#ffa359',
      operator: '#08c0ef',
      attribute: '#ffd452',
    },
    ansi: {
      red: '#ff2e3f',
      green: '#0dbe4e',
      yellow: '#ffca00',
      blue: '#009fff',
      magenta: '#e130ac',
      cyan: '#08c0ef',
    },
  },
  {
    id: 'pierre-light',
    name: 'Pierre Light',
    family: 'Pierre',
    scheme: 'light',
    canvas: '#ffffff',
    sidebar: '#f5f5f5',
    raised: '#ffffff',
    text: '#0a0a0a',
    accent: '#009fff',
    success: '#15803d',
    warning: '#936c00',
    danger: '#d52c36',
    syntax: {
      keyword: '#d32a61',
      string: '#16833a',
      number: '#127a99',
      function: '#693acf',
      type: '#a631be',
      comment: '#737373',
      variable: '#a85a14',
      property: '#a85a14',
      operator: '#127a99',
      attribute: '#936c00',
    },
    ansi: {
      red: '#d52c36',
      green: '#18a46c',
      yellow: '#9c7a00',
      blue: '#1a85d4',
      magenta: '#bd2e90',
      cyan: '#168ab0',
    },
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    family: 'One',
    scheme: 'dark',
    canvas: '#282c34',
    sidebar: '#21252b',
    raised: '#2f343e',
    text: '#abb2bf',
    accent: '#61afef',
    accentSecondary: '#56b6c2',
    success: '#98c379',
    warning: '#e5c07b',
    danger: '#e06c75',
    syntax: {
      keyword: '#c678dd',
      string: '#98c379',
      number: '#d19a66',
      function: '#61afef',
      type: '#e5c07b',
      comment: '#7f848e',
      property: '#e06c75',
      operator: '#56b6c2',
      tag: '#e06c75',
      attribute: '#d19a66',
    },
    ansi: {
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
    },
  },
  {
    id: 'one-light',
    name: 'One Light',
    family: 'One',
    scheme: 'light',
    canvas: '#fafafa',
    sidebar: '#eaeaeb',
    raised: '#ffffff',
    text: '#383a42',
    accent: '#526fff',
    success: '#3d8b3c',
    warning: '#986801',
    danger: '#c8432f',
    syntax: {
      keyword: '#a626a4',
      string: '#3e8a3d',
      number: '#986801',
      function: '#3666d6',
      type: '#936500',
      comment: '#80818a',
      property: '#c8432f',
      operator: '#0176a8',
      tag: '#c8432f',
      attribute: '#986801',
    },
    ansi: {
      red: '#e45649',
      green: '#50a14f',
      yellow: '#a87400',
      blue: '#4078f2',
      magenta: '#a626a4',
      cyan: '#0184bc',
    },
  },
  {
    id: 'vercel-dark',
    name: 'Vercel Dark',
    family: 'Vercel',
    scheme: 'dark',
    canvas: '#0a0a0a',
    sidebar: '#000000',
    raised: '#1a1a1a',
    text: '#ededed',
    muted: '#a1a1a1',
    accent: '#52a8ff',
    success: '#62c073',
    warning: '#ffb224',
    danger: '#ff6166',
    syntax: {
      keyword: '#f75f8f',
      string: '#62c073',
      number: '#ffb224',
      function: '#c472fb',
      type: '#52a8ff',
      comment: '#8f8f8f',
    },
    ansi: {
      red: '#ff6166',
      green: '#62c073',
      yellow: '#ffb224',
      blue: '#52a8ff',
      magenta: '#c472fb',
      cyan: '#0ac7b4',
    },
  },
  {
    id: 'vercel-light',
    name: 'Vercel Light',
    family: 'Vercel',
    scheme: 'light',
    canvas: '#ffffff',
    sidebar: '#fafafa',
    raised: '#ffffff',
    text: '#171717',
    muted: '#666666',
    accent: '#006bff',
    success: '#107d32',
    warning: '#a35200',
    danger: '#d8001b',
    syntax: {
      keyword: '#c41562',
      string: '#107d32',
      number: '#a35200',
      function: '#7d00cc',
      type: '#005ff2',
      comment: '#666666',
    },
    ansi: {
      red: '#d8001b',
      green: '#107d32',
      yellow: '#a35200',
      blue: '#006bff',
      magenta: '#7d00cc',
      cyan: '#00797a',
    },
  },
  {
    id: 'vscode-plus-dark',
    name: 'VS Code Plus Dark',
    family: 'VS Code Plus',
    scheme: 'dark',
    canvas: '#1e1e1e',
    sidebar: '#252526',
    raised: '#2d2d30',
    text: '#d4d4d4',
    accent: '#0078d4',
    accentSecondary: '#3794ff',
    success: '#89d185',
    warning: '#cca700',
    danger: '#f14c4c',
    syntax: {
      keyword: '#569cd6',
      string: '#ce9178',
      number: '#b5cea8',
      function: '#dcdcaa',
      type: '#4ec9b0',
      comment: '#6a9955',
      variable: '#9cdcfe',
      property: '#9cdcfe',
      operator: '#d4d4d4',
      tag: '#569cd6',
      attribute: '#9cdcfe',
      meta: '#c586c0',
    },
    ansi: {
      red: '#f14c4c',
      green: '#23d18b',
      yellow: '#e5e510',
      blue: '#3b8eea',
      magenta: '#d670d6',
      cyan: '#29b8db',
    },
  },
  {
    id: 'vscode-plus-light',
    name: 'VS Code Plus Light',
    family: 'VS Code Plus',
    scheme: 'light',
    canvas: '#ffffff',
    sidebar: '#f3f3f3',
    raised: '#ffffff',
    text: '#1f1f1f',
    accent: '#005fb8',
    success: '#388a34',
    warning: '#8f6400',
    danger: '#cd3131',
    syntax: {
      keyword: '#0000ff',
      string: '#a31515',
      number: '#098658',
      function: '#795e26',
      type: '#267f99',
      comment: '#008000',
      variable: '#001080',
      property: '#001080',
      tag: '#800000',
      attribute: '#e50000',
      meta: '#af00db',
    },
    ansi: {
      red: '#cd3131',
      green: '#107c10',
      yellow: '#7f8300',
      blue: '#0451a5',
      magenta: '#bc05bc',
      cyan: '#0598bc',
    },
  },
  {
    id: 'xcode-dark',
    name: 'Xcode Dark',
    family: 'Xcode',
    scheme: 'dark',
    canvas: '#1f1f24',
    sidebar: '#26262b',
    raised: '#2e2e33',
    text: '#dfdfe0',
    accent: '#0a84ff',
    success: '#32d74b',
    warning: '#ffd60a',
    danger: '#ff453a',
    syntax: {
      keyword: '#fc5fa3',
      string: '#fc6a5d',
      number: '#d0bf69',
      function: '#67b7a4',
      type: '#5dd8ff',
      comment: '#7f8c98',
      property: '#a167e6',
      attribute: '#bf8555',
      meta: '#fd8f3f',
    },
    ansi: {
      red: '#ff453a',
      green: '#32d74b',
      yellow: '#ffd60a',
      blue: '#0a84ff',
      magenta: '#bf5af2',
      cyan: '#64d2ff',
    },
  },
  {
    id: 'xcode-light',
    name: 'Xcode Light',
    family: 'Xcode',
    scheme: 'light',
    canvas: '#ffffff',
    sidebar: '#f2f2f4',
    raised: '#ffffff',
    text: '#262626',
    accent: '#007aff',
    success: '#248a3d',
    warning: '#9a5b00',
    danger: '#d70015',
    syntax: {
      keyword: '#9b2393',
      string: '#c41a16',
      number: '#1c00cf',
      function: '#326d74',
      type: '#0b4f79',
      comment: '#5d6c79',
      property: '#3900a0',
      attribute: '#815f03',
      meta: '#643820',
    },
    ansi: {
      red: '#d70015',
      green: '#248a3d',
      yellow: '#9a5b00',
      blue: '#0040dd',
      magenta: '#ad1d8f',
      cyan: '#0071a4',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    family: 'Gruvbox',
    scheme: 'dark',
    canvas: '#282828',
    sidebar: '#1d2021',
    raised: '#3c3836',
    text: '#ebdbb2',
    muted: '#a89984',
    accent: '#8ec07c',
    accentSecondary: '#83a598',
    success: '#b8bb26',
    warning: '#fabd2f',
    danger: '#fb4934',
    syntax: {
      keyword: '#fb4934',
      string: '#b8bb26',
      number: '#d3869b',
      function: '#fabd2f',
      type: '#8ec07c',
      comment: '#928374',
      property: '#83a598',
      operator: '#fe8019',
      tag: '#83a598',
      attribute: '#fabd2f',
      meta: '#fe8019',
    },
    ansi: {
      red: '#fb4934',
      green: '#b8bb26',
      yellow: '#fabd2f',
      blue: '#83a598',
      magenta: '#d3869b',
      cyan: '#8ec07c',
    },
  },
  {
    id: 'gruvbox-light',
    name: 'Gruvbox Light',
    family: 'Gruvbox',
    scheme: 'light',
    canvas: '#fbf1c7',
    sidebar: '#f2e5bc',
    raised: '#f9f5d7',
    text: '#3c3836',
    muted: '#665c54',
    accent: '#427b58',
    accentSecondary: '#076678',
    success: '#6f6a0c',
    warning: '#8f5a0a',
    danger: '#9d0006',
    syntax: {
      keyword: '#9d0006',
      string: '#6f6a0c',
      number: '#8f3f71',
      function: '#8f5a0a',
      type: '#427b58',
      comment: '#7c6f64',
      property: '#076678',
      operator: '#af3a03',
      tag: '#076678',
      attribute: '#8f5a0a',
      meta: '#af3a03',
    },
    ansi: {
      red: '#9d0006',
      green: '#79740e',
      yellow: '#9a620f',
      blue: '#076678',
      magenta: '#8f3f71',
      cyan: '#427b58',
    },
  },
  {
    id: 'linear-dark',
    name: 'Linear Dark',
    family: 'Linear',
    scheme: 'dark',
    canvas: '#0f1011',
    sidebar: '#08090a',
    raised: '#1b1c1e',
    text: '#e2e4e7',
    muted: '#8a8f98',
    accent: '#5e6ad2',
    accentSecondary: '#7170ff',
    success: '#4cb782',
    warning: '#f2c94c',
    danger: '#eb5757',
    syntax: {
      keyword: '#9ea3ff',
      string: '#76c7a0',
      number: '#f0b86e',
      function: '#d2d6ff',
      type: '#6fc2e6',
      comment: '#6f737b',
      attribute: '#e4a7e8',
      meta: '#e4a7e8',
    },
    ansi: {
      red: '#eb5757',
      green: '#4cb782',
      yellow: '#f2c94c',
      blue: '#6b7ff0',
      magenta: '#b28cf0',
      cyan: '#4ec3d8',
    },
  },
  {
    id: 'linear-light',
    name: 'Linear Light',
    family: 'Linear',
    scheme: 'light',
    canvas: '#fcfcfd',
    sidebar: '#f4f4f6',
    raised: '#ffffff',
    text: '#1d1e22',
    muted: '#62666d',
    accent: '#5e6ad2',
    success: '#27875b',
    warning: '#9a6200',
    danger: '#d33d3d',
    syntax: {
      keyword: '#4f59c2',
      string: '#23855a',
      number: '#a0540a',
      function: '#6a3fc0',
      type: '#1c7aa1',
      comment: '#747880',
      attribute: '#9b3fa3',
      meta: '#9b3fa3',
    },
    ansi: {
      red: '#d33d3d',
      green: '#27875b',
      yellow: '#9a6200',
      blue: '#4f59c2',
      magenta: '#8a45c8',
      cyan: '#1c7aa1',
    },
  },
  {
    id: 'notion-dark',
    name: 'Notion Dark',
    family: 'Notion',
    scheme: 'dark',
    canvas: '#191919',
    sidebar: '#202020',
    raised: '#252525',
    text: '#d4d4d4',
    muted: '#9b9b9b',
    accent: '#2383e2',
    accentSecondary: '#529cca',
    success: '#4dab9a',
    warning: '#ffa344',
    danger: '#ff7369',
    syntax: {
      keyword: '#b48ce8',
      string: '#5fbfa8',
      number: '#ffa344',
      function: '#529cca',
      type: '#e6c44a',
      comment: '#8b8b8b',
      tag: '#ff7369',
      attribute: '#ffa344',
    },
    ansi: {
      red: '#ff7369',
      green: '#4dab9a',
      yellow: '#ffdc49',
      blue: '#529cca',
      magenta: '#9a6dd7',
      cyan: '#4dabbf',
    },
  },
  {
    id: 'notion-light',
    name: 'Notion Light',
    family: 'Notion',
    scheme: 'light',
    canvas: '#ffffff',
    sidebar: '#f7f7f5',
    raised: '#ffffff',
    text: '#37352f',
    muted: '#6f6e6a',
    accent: '#2383e2',
    success: '#0f7b6c',
    warning: '#b8600b',
    danger: '#c93636',
    syntax: {
      keyword: '#6940a5',
      string: '#0f7b6c',
      number: '#b8600b',
      function: '#0b6e99',
      type: '#8a6500',
      comment: '#787774',
      tag: '#c93636',
      attribute: '#b8600b',
    },
    ansi: {
      red: '#e03e3e',
      green: '#0f7b6c',
      yellow: '#a87e00',
      blue: '#0b6e99',
      magenta: '#6940a5',
      cyan: '#0f7b8f',
    },
  },
  {
    id: 'proof-dark',
    name: 'Proof Dark',
    family: 'Proof',
    scheme: 'dark',
    note: 'sage · for reading',
    canvas: '#1a1d19',
    sidebar: '#141613',
    raised: '#232722',
    text: '#dfe3d6',
    muted: '#9aa391',
    accent: '#8fbf9b',
    accentSecondary: '#8fb3c0',
    success: '#8fbf8a',
    warning: '#d8b465',
    danger: '#e2877c',
    syntax: {
      keyword: '#8fc6a4',
      string: '#d6b57e',
      number: '#e0a08a',
      function: '#9fbde0',
      type: '#c2a8e8',
      comment: '#7c8574',
      attribute: '#d6b57e',
    },
    ansi: {
      red: '#e2877c',
      green: '#8fbf8a',
      yellow: '#d8b465',
      blue: '#8fb3e0',
      magenta: '#c2a8e8',
      cyan: '#7fc4bb',
    },
  },
  {
    id: 'proof-light',
    name: 'Proof Light',
    family: 'Proof',
    scheme: 'light',
    note: 'sage · for reading',
    canvas: '#f4f5ef',
    sidebar: '#eaece3',
    raised: '#fbfbf8',
    text: '#23281f',
    muted: '#5e6558',
    accent: '#3d6b4f',
    accentSecondary: '#4f7584',
    success: '#3d7a45',
    warning: '#8a5f10',
    danger: '#b0443a',
    syntax: {
      keyword: '#2f6b52',
      string: '#8a5a25',
      number: '#9a4a35',
      function: '#355f8a',
      type: '#6a5096',
      comment: '#747b6e',
      attribute: '#8a5a25',
    },
    ansi: {
      red: '#b0443a',
      green: '#3d7a45',
      yellow: '#8a6512',
      blue: '#355f8a',
      magenta: '#7a4e8f',
      cyan: '#2f7470',
    },
  },
  {
    id: 'raycast-dark',
    name: 'Raycast Dark',
    family: 'Raycast',
    scheme: 'dark',
    canvas: '#18181a',
    sidebar: '#111113',
    raised: '#232326',
    text: '#ececec',
    muted: '#9a9a9f',
    accent: '#ff6363',
    accentSecondary: '#ff9f6b',
    success: '#59d499',
    warning: '#ffc531',
    danger: '#f2555a',
    syntax: {
      keyword: '#ff6363',
      string: '#59d499',
      number: '#ffc531',
      function: '#56c2ff',
      type: '#cf9bff',
      comment: '#7a7a80',
      attribute: '#ffc531',
    },
    ansi: {
      red: '#ff6363',
      green: '#59d499',
      yellow: '#ffc531',
      blue: '#56c2ff',
      magenta: '#cf9bff',
      cyan: '#5ed8d8',
    },
  },
  {
    id: 'raycast-light',
    name: 'Raycast Light',
    family: 'Raycast',
    scheme: 'light',
    canvas: '#ffffff',
    sidebar: '#f6f6f7',
    raised: '#ffffff',
    text: '#151517',
    muted: '#66666c',
    accent: '#e5484d',
    success: '#12805c',
    warning: '#9a6200',
    danger: '#c9303a',
    syntax: {
      keyword: '#d23a42',
      string: '#12805c',
      number: '#9a6200',
      function: '#0b6fbd',
      type: '#8a3fd1',
      comment: '#75757b',
      attribute: '#9a6200',
    },
    ansi: {
      red: '#d7373f',
      green: '#12805c',
      yellow: '#9a6400',
      blue: '#0b6fbd',
      magenta: '#8a3fd1',
      cyan: '#0e7c86',
    },
  },
];

export const EDITOR_THEMES = Object.fromEntries(
  THEME_ANCHORS.map((anchors) => [anchors.id, editorTheme(anchors)]),
) as Record<
  Exclude<ThemeId, 'nightglass' | 'tide' | 'graphite' | 'oled' | 'frost' | 'linen'>,
  ThemeDefinition
>;
