//! Claude Code's own session history, read from the transcripts it keeps in
//! `<config>/projects/<folder>/<session ID>.jsonl` (`CLAUDE_CONFIG_DIR`, or
//! `~/.claude`). Claude Code documents where they are but calls the entry
//! format internal, so this reader is deliberately narrow: it uses a few
//! long-standing fields, skips every line it does not recognize, and never
//! writes, moves or deletes a file. It reads nothing outside `projects`, so
//! never Claude's credentials.
//!
//! A listing reads only the start and end of each transcript; a read rebuilds
//! the conversation's current branch (edits and rewinds leave abandoned ones
//! in the file) by following each entry's parent back from the last.
use super::{ClaudeAdapter, tools};
use crate::{
    error::JamError,
    protocol::MessageBlock,
    providers::{
        HistoryFuture, HistoryItem, HistoryItemRequest, HistoryListRequest, HistoryMessage,
        HistoryPage, HistoryReadRequest, HistoryTranscript, ProviderHistory,
    },
};
use serde_json::Value;
use std::{
    collections::{HashMap, HashSet},
    fs::File,
    io::{BufRead, BufReader, Read, Seek, SeekFrom},
    path::{Path, PathBuf},
    time::SystemTime,
};

/// The most transcripts listed, and the most bytes read from the start and
/// the end of each for its metadata.
const LIST_LIMIT: usize = 20_000;
const HEAD_BYTES: u64 = 256 * 1024;
const TAIL_BYTES: u64 = 64 * 1024;
/// The largest transcript read, and the longest line parsed in one.
const READ_BYTES: u64 = 256 * 1024 * 1024;
const LINE_BYTES: usize = 16 * 1024 * 1024;
/// Text Claude Code adds to a user turn on its own (slash commands, their
/// output, reminders, background tasks finishing); it is not something the
/// reader said.
const GENERATED: &[&str] = &[
    "<task-notification>",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<local-command-caveat>",
    "<system-reminder>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "Caveat: The messages below were generated by the user while running local commands.",
];

impl ProviderHistory for ClaudeAdapter {
    fn list(&self, request: HistoryListRequest) -> HistoryFuture<HistoryPage> {
        Box::pin(async move {
            tokio::task::spawn_blocking(move || {
                let Some(root) = projects_dir() else {
                    return Ok(HistoryPage::default());
                };
                list(
                    &root,
                    &request.folders,
                    request.page.as_deref(),
                    request.limit,
                )
            })
            .await
            .map_err(|_| JamError::new("internal", "Claude Code's history could not be read."))?
        })
    }

    fn read(&self, request: HistoryReadRequest) -> HistoryFuture<HistoryTranscript> {
        Box::pin(async move {
            tokio::task::spawn_blocking(move || {
                let missing = || JamError::new("not_found", "Claude Code no longer has this chat.");
                let root = projects_dir().ok_or_else(missing)?;
                let path = transcript(&root, &request.native_id).ok_or_else(missing)?;
                read(&path, request.page.as_deref(), request.limit)
            })
            .await
            .map_err(|_| JamError::new("internal", "Claude Code's history could not be read."))?
        })
    }

    fn item(&self, request: HistoryItemRequest) -> HistoryFuture<Option<HistoryItem>> {
        Box::pin(async move {
            tokio::task::spawn_blocking(move || {
                Ok(projects_dir()
                    .and_then(|root| transcript(&root, &request.native_id))
                    .and_then(|path| item(&path)))
            })
            .await
            .map_err(|_| JamError::new("internal", "Claude Code's history could not be read."))?
        })
    }
}

/// Where Claude Code keeps its transcripts, the way it finds its own
/// configuration folder.
fn projects_dir() -> Option<PathBuf> {
    let config = std::env::var_os("CLAUDE_CONFIG_DIR")
        .filter(|dir| !dir.is_empty())
        .map(PathBuf::from)
        .or_else(|| std::env::home_dir().map(|home| home.join(".claude")))?;
    Some(config.join("projects"))
}

/// A Claude session ID: a UUID in practice. Anything else, and anything that
/// could name another path, is not one.
fn session_id(text: &str) -> bool {
    !text.is_empty()
        && text.len() <= 64
        && text.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
}

/// Whether Claude Code may keep transcripts for one of `folders` in the
/// folder named `name`. It names that folder after the working directory with
/// every character but ASCII letters and digits replaced by `-`, and
/// shortens a long one with a hash, which is not matched here, so a long name
/// is always read. Only a hint: the runtime matches the reported folder.
fn may_hold(name: &str, folders: &[String]) -> bool {
    const SHORTENED: usize = 200;
    if folders.is_empty() || name.len() >= SHORTENED {
        return true;
    }
    folders.iter().any(|folder| {
        let encoded: String = folder
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
            .collect();
        encoded.eq_ignore_ascii_case(name)
            || encoded.trim_end_matches('-').eq_ignore_ascii_case(name)
    })
}

/// Every transcript, or those that may be from `folders`, in a stable order
/// (folder, then file), so pages continue where they left off even while
/// Claude Code writes to them.
fn transcripts(root: &Path, folders: &[String]) -> Vec<PathBuf> {
    let wanted = folders;
    let mut found = Vec::new();
    let Ok(folders) = std::fs::read_dir(root) else {
        return found;
    };
    let mut folders: Vec<PathBuf> = folders
        .flatten()
        .filter(|entry| {
            entry.file_type().is_ok_and(|kind| kind.is_dir())
                && entry
                    .file_name()
                    .to_str()
                    .is_some_and(|name| may_hold(name, wanted))
        })
        .map(|entry| entry.path())
        .collect();
    folders.sort();
    for folder in folders {
        let Ok(files) = std::fs::read_dir(&folder) else {
            continue;
        };
        let mut files: Vec<PathBuf> = files
            .flatten()
            .filter(|entry| entry.file_type().is_ok_and(|kind| kind.is_file()))
            .map(|entry| entry.path())
            .filter(|path| {
                path.extension().is_some_and(|ext| ext == "jsonl")
                    && path
                        .file_stem()
                        .and_then(|stem| stem.to_str())
                        .is_some_and(session_id)
            })
            .collect();
        files.sort();
        found.extend(files);
        if found.len() >= LIST_LIMIT {
            found.truncate(LIST_LIMIT);
            break;
        }
    }
    found
}

/// The transcript for a session. When more than one folder has it (a
/// session resumed elsewhere), the one written last.
fn transcript(root: &Path, native_id: &str) -> Option<PathBuf> {
    if !session_id(native_id) {
        return None;
    }
    let name = format!("{native_id}.jsonl");
    std::fs::read_dir(root)
        .ok()?
        .flatten()
        .map(|folder| folder.path().join(&name))
        .filter_map(|path| {
            let meta = std::fs::symlink_metadata(&path).ok()?;
            meta.is_file().then(|| (meta.modified().ok(), path))
        })
        .max_by_key(|(modified, _)| *modified)
        .map(|(_, path)| path)
}

fn list(
    root: &Path,
    folders: &[String],
    page: Option<&str>,
    limit: usize,
) -> Result<HistoryPage, JamError> {
    let start = match page {
        None => 0,
        Some(page) => page
            .parse::<usize>()
            .map_err(|_| JamError::invalid("That history page is not valid."))?,
    };
    let all = transcripts(root, folders);
    let end = (start + limit.max(1)).min(all.len());
    let items = all
        .get(start..end)
        .unwrap_or_default()
        .iter()
        .filter_map(|path| item(path))
        .collect();
    Ok(HistoryPage {
        items,
        next_page: (end < all.len()).then(|| end.to_string()),
    })
}

/// One transcript's listing metadata, from its start and end only. A file
/// with no conversation in it (only a title, say) is not a chat.
fn item(path: &Path) -> Option<HistoryItem> {
    let native_id = path.file_stem()?.to_str()?.to_owned();
    let meta = std::fs::symlink_metadata(path).ok()?;
    let modified = meta.modified().ok();
    let mut file = File::open(path).ok()?;
    let mut head = Summary::default();
    for line in lines(&mut file, HEAD_BYTES) {
        head.take(&line);
    }
    head.first_prompt.as_ref().or(head.first_reply.as_ref())?;
    if meta.len() > HEAD_BYTES && file.seek(SeekFrom::End(-(TAIL_BYTES as i64))).is_ok() {
        // The first line of the tail is usually cut short and fails to parse.
        for line in lines(&mut file, TAIL_BYTES) {
            head.take_latest(&line);
        }
    }
    Some(HistoryItem {
        native_id,
        title: head
            .title()
            .or(head.first_prompt.as_deref())
            .map(str::to_owned),
        preview: head.first_prompt.clone(),
        created_at: head.created_at.clone(),
        updated_at: modified.and_then(rfc3339),
        revision: Some(format!(
            "{}:{}",
            meta.len(),
            modified
                .and_then(|time| time.duration_since(SystemTime::UNIX_EPOCH).ok())
                .map_or(0, |since| since.as_nanos())
        )),
        cwd: head.cwd,
        branch: head.branch,
        resumable: true,
    })
}

/// What a listing learns from a transcript's lines.
#[derive(Default)]
struct Summary {
    cwd: Option<String>,
    created_at: Option<String>,
    first_prompt: Option<String>,
    first_reply: Option<String>,
    custom_title: Option<String>,
    ai_title: Option<String>,
    summary: Option<String>,
    branch: Option<String>,
}

impl Summary {
    fn take(&mut self, entry: &Value) {
        self.take_latest(entry);
        if self.cwd.is_none() {
            self.cwd = text(entry, "cwd").map(str::to_owned);
        }
        if self.created_at.is_none() {
            self.created_at = text(entry, "timestamp").map(str::to_owned);
        }
        if !conversation(entry) {
            return;
        }
        match text(entry, "type") {
            Some("user") if self.first_prompt.is_none() => {
                let (said, _) = user_content(entry);
                self.first_prompt = (!said.is_empty()).then(|| said.join("\n"));
            }
            Some("assistant") if self.first_reply.is_none() => {
                self.first_reply = Some(String::new());
            }
            _ => {}
        }
    }

    /// The newest of each kind of title, and the branch last worked on.
    fn take_latest(&mut self, entry: &Value) {
        if let Some(branch) = text(entry, "gitBranch").filter(|b| !b.trim().is_empty()) {
            self.branch = Some(branch.to_owned());
        }
        let found = |key| {
            text(entry, key)
                .filter(|t| !t.trim().is_empty())
                .map(str::to_owned)
        };
        match text(entry, "type") {
            Some("custom-title") => {
                self.custom_title = found("customTitle").or(self.custom_title.take())
            }
            Some("ai-title") => self.ai_title = found("aiTitle").or(self.ai_title.take()),
            Some("summary") => self.summary = found("summary").or(self.summary.take()),
            _ => {}
        }
    }

    /// Claude Code's own order: the reader's name for it, a generated title,
    /// then an older summary. Without one, the first prompt names it.
    fn title(&self) -> Option<&str> {
        self.custom_title
            .as_deref()
            .or(self.ai_title.as_deref())
            .or(self.summary.as_deref())
    }
}

fn read(path: &Path, page: Option<&str>, limit: usize) -> Result<HistoryTranscript, JamError> {
    let start = match page {
        None => 0,
        Some(page) => page
            .parse::<usize>()
            .map_err(|_| JamError::invalid("That history page is not valid."))?,
    };
    let mut file = File::open(path)
        .map_err(|_| JamError::new("not_found", "Claude Code no longer has this chat."))?;
    if file.metadata().is_ok_and(|meta| meta.len() > READ_BYTES) {
        return Err(JamError::new(
            "provider_error",
            "This Claude Code chat is too long to bring into JAM Code.",
        ));
    }
    let entries: Vec<Value> = lines(&mut file, READ_BYTES).collect();
    let messages = messages(&entries);
    let end = (start + limit.max(1)).min(messages.len());
    Ok(HistoryTranscript {
        item: None,
        messages: messages.get(start..end).unwrap_or_default().to_vec(),
        next_page: (end < messages.len()).then(|| end.to_string()),
        checkpoint: None,
    })
}

/// A transcript's current branch as JAM messages: each thing the reader said
/// as its own message, and everything the agent did until the next as one
/// reply. Entry IDs keep both stable across syncs.
fn messages(entries: &[Value]) -> Vec<HistoryMessage> {
    let branch = current_branch(entries);
    let mut out = Vec::new();
    let mut reply: Option<Reply> = None;
    let mut kinds: HashMap<String, String> = HashMap::new();
    for entry in entries {
        if !conversation(entry) {
            continue;
        }
        let Some(id) = text(entry, "uuid") else {
            continue;
        };
        if !branch.as_ref().is_none_or(|branch| branch.contains(id)) {
            continue;
        }
        let cwd = text(entry, "cwd").map(Path::new);
        match text(entry, "type") {
            Some("user") => {
                let (said, results) = user_content(entry);
                if let Some(reply) = reply.as_mut() {
                    for result in results {
                        reply.finish_tool(result, &kinds);
                    }
                }
                if !said.is_empty() {
                    out.extend(reply.take().and_then(Reply::message));
                    out.push(HistoryMessage {
                        source_id: id.to_owned(),
                        role: "user".into(),
                        created_at: text(entry, "timestamp").map(str::to_owned),
                        blocks: vec![MessageBlock::Text {
                            text: said.join("\n"),
                        }],
                    });
                }
            }
            Some("assistant") => {
                let reply = reply.get_or_insert_with(|| Reply {
                    source_id: id.to_owned(),
                    created_at: text(entry, "timestamp").map(str::to_owned),
                    blocks: Vec::new(),
                });
                for block in content(entry) {
                    match text(block, "type") {
                        Some("text") => {
                            if let Some(said) = text(block, "text").filter(|t| !t.trim().is_empty())
                            {
                                reply.blocks.push(MessageBlock::Text {
                                    text: said.to_owned(),
                                });
                            }
                        }
                        Some("thinking") => {
                            if let Some(thought) =
                                text(block, "thinking").filter(|t| !t.trim().is_empty())
                            {
                                reply.blocks.push(MessageBlock::Reasoning {
                                    text: thought.to_owned(),
                                });
                            }
                        }
                        Some("tool_use") => {
                            let (Some(tool_id), Some(name)) =
                                (text(block, "id"), text(block, "name"))
                            else {
                                continue;
                            };
                            if tools::hidden(name) {
                                continue;
                            }
                            let input = block.get("input").cloned().unwrap_or(Value::Null);
                            let tool = tools::tool_block(tool_id, name, &input, "completed", cwd);
                            if let MessageBlock::Tool { kind, .. } = &tool {
                                kinds.insert(tool_id.to_owned(), kind.clone());
                            }
                            reply.blocks.push(tool);
                        }
                        _ => {}
                    }
                }
            }
            _ => {}
        }
    }
    out.extend(reply.and_then(Reply::message));
    out
}

/// The agent's reply being gathered from consecutive assistant entries.
struct Reply {
    source_id: String,
    created_at: Option<String>,
    blocks: Vec<MessageBlock>,
}

impl Reply {
    fn message(self) -> Option<HistoryMessage> {
        (!self.blocks.is_empty()).then(|| HistoryMessage {
            source_id: self.source_id,
            role: "assistant".into(),
            created_at: self.created_at,
            blocks: self.blocks,
        })
    }

    /// Records a tool's result on its block: failed or completed, with its
    /// output where the live transcript would show it.
    fn finish_tool(&mut self, result: &Value, kinds: &HashMap<String, String>) {
        let Some(tool_id) = text(result, "tool_use_id") else {
            return;
        };
        let failed = result.get("is_error").and_then(Value::as_bool) == Some(true);
        let shows = kinds
            .get(tool_id)
            .is_some_and(|kind| tools::shows_output(kind));
        for block in self.blocks.iter_mut().rev() {
            if let MessageBlock::Tool {
                id, status, detail, ..
            } = block
                && id == tool_id
            {
                if failed {
                    *status = "failed".into();
                }
                if shows || failed {
                    let output = tools::result_text(result.get("content"));
                    if !output.is_empty() {
                        *detail = if detail.is_empty() {
                            output
                        } else {
                            format!("{detail}\n{output}")
                        };
                    }
                }
                return;
            }
        }
    }
}

/// The IDs on the conversation's current branch: from the last entry back
/// through each parent, across compactions (which restart the chain and
/// point back with `logicalParentUuid`). `None` when the file has no
/// usable chain, and then every entry is kept in file order.
fn current_branch(entries: &[Value]) -> Option<HashSet<String>> {
    let mut parents: HashMap<&str, Option<&str>> = HashMap::new();
    let mut last = None;
    for entry in entries {
        let Some(id) = text(entry, "uuid") else {
            continue;
        };
        let parent = text(entry, "parentUuid").or_else(|| text(entry, "logicalParentUuid"));
        parents.insert(id, parent);
        if conversation(entry) {
            last = Some(id);
        }
    }
    let mut branch = HashSet::new();
    let mut at = last;
    while let Some(id) = at {
        if !branch.insert(id.to_owned()) {
            break;
        }
        at = parents.get(id).copied().flatten();
    }
    (!branch.is_empty()).then_some(branch)
}

/// A user or assistant entry of the main conversation: not a sub-agent's,
/// not one Claude Code added for itself, and not a compaction summary.
fn conversation(entry: &Value) -> bool {
    let flag = |key| entry.get(key).and_then(Value::as_bool) == Some(true);
    matches!(text(entry, "type"), Some("user" | "assistant"))
        && !flag("isSidechain")
        && !flag("isMeta")
        && !flag("isCompactSummary")
        && !flag("isVisibleInTranscriptOnly")
}

fn content(entry: &Value) -> impl Iterator<Item = &Value> {
    entry
        .pointer("/message/content")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
}

/// What the reader said in a user entry, and the tool results it carries.
fn user_content(entry: &Value) -> (Vec<String>, Vec<&Value>) {
    // A turn Claude Code started itself (`promptSource: "system"`, such as a
    // background task finishing) says nothing the reader said.
    let generated = text(entry, "promptSource") == Some("system");
    let said_text = |text: &str| {
        let text = text.trim();
        (!generated && !text.is_empty() && !GENERATED.iter().any(|mark| text.starts_with(mark)))
            .then(|| text.to_owned())
    };
    if let Some(text) = entry.pointer("/message/content").and_then(Value::as_str) {
        return (said_text(text).into_iter().collect(), Vec::new());
    }
    let mut said = Vec::new();
    let mut results = Vec::new();
    for block in content(entry) {
        match text(block, "type") {
            Some("text") => said.extend(text(block, "text").and_then(said_text)),
            Some("image") => said.push("[image]".into()),
            Some("tool_result") => results.push(block),
            _ => {}
        }
    }
    // An image alone is still something the reader sent.
    (said, results)
}

/// Parsed lines from where the file is now, up to `limit` bytes. A line that
/// is not JSON (or is cut short at either end) is skipped.
fn lines(file: &mut File, limit: u64) -> impl Iterator<Item = Value> + '_ {
    let mut reader = BufReader::new(Read::take(file, limit));
    let mut buffer = Vec::new();
    std::iter::from_fn(move || {
        loop {
            buffer.clear();
            match reader.read_until(b'\n', &mut buffer) {
                Ok(0) | Err(_) => return None,
                Ok(_) if buffer.len() > LINE_BYTES => continue,
                Ok(_) => {
                    if let Ok(value) = serde_json::from_slice::<Value>(&buffer)
                        && value.is_object()
                    {
                        return Some(value);
                    }
                }
            }
        }
    })
}

fn text<'a>(value: &'a Value, key: &str) -> Option<&'a str> {
    value.get(key).and_then(Value::as_str)
}

fn rfc3339(time: SystemTime) -> Option<String> {
    time::OffsetDateTime::from(time)
        .format(&time::format_description::well_known::Rfc3339)
        .ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// A folder of its own for one test, removed afterwards.
    struct Scratch(PathBuf);

    impl Scratch {
        fn new() -> Self {
            let dir =
                std::env::temp_dir().join(format!("jam-claude-history-{}", uuid::Uuid::new_v4()));
            std::fs::create_dir_all(&dir).unwrap();
            Self(dir)
        }

        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    fn write(dir: &Path, folder: &str, id: &str, entries: &[Value]) -> PathBuf {
        let folder = dir.join(folder);
        std::fs::create_dir_all(&folder).unwrap();
        let path = folder.join(format!("{id}.jsonl"));
        let mut text = String::new();
        for entry in entries {
            text.push_str(&entry.to_string());
            text.push('\n');
        }
        std::fs::write(&path, text).unwrap();
        path
    }

    fn user(id: &str, parent: Option<&str>, content: Value) -> Value {
        json!({"type": "user", "uuid": id, "parentUuid": parent, "cwd": "/work/jam",
               "timestamp": "2026-10-01T10:00:00.000Z", "message": {"role": "user", "content": content}})
    }

    fn assistant(id: &str, parent: &str, content: Value) -> Value {
        json!({"type": "assistant", "uuid": id, "parentUuid": parent, "cwd": "/work/jam",
               "timestamp": "2026-10-01T10:00:05.000Z", "message": {"role": "assistant", "content": content}})
    }

    #[test]
    fn a_listing_names_each_chat_by_its_newest_title_and_skips_empty_ones() {
        let dir = Scratch::new();
        write(
            dir.path(),
            "-work-jam",
            "a1",
            &[
                json!({"type": "queue-operation", "operation": "enqueue"}),
                user("u1", None, json!("Fix the parser")),
                json!({"type": "ai-title", "aiTitle": "Parser fix"}),
                assistant("r1", "u1", json!([{"type": "text", "text": "Done."}])),
                json!({"type": "custom-title", "customTitle": "My parser", "gitBranch": "feat/parser"}),
            ],
        );
        // Only a title: not a conversation.
        write(
            dir.path(),
            "-work-jam",
            "b2",
            &[json!({"type": "ai-title", "aiTitle": "Nothing"})],
        );
        // Not a session ID, so never listed or opened.
        write(
            dir.path(),
            "-work-jam",
            "not.an.id",
            &[user("u9", None, json!("hi"))],
        );
        let page = list(dir.path(), &[], None, 10).unwrap();
        assert_eq!(page.items.len(), 1);
        let item = &page.items[0];
        assert_eq!(item.native_id, "a1");
        assert_eq!(item.title.as_deref(), Some("My parser"));
        assert_eq!(item.preview.as_deref(), Some("Fix the parser"));
        assert_eq!(item.cwd.as_deref(), Some("/work/jam"));
        assert_eq!(item.branch.as_deref(), Some("feat/parser"));
        assert_eq!(item.created_at.as_deref(), Some("2026-10-01T10:00:00.000Z"));
        assert!(item.revision.is_some() && item.updated_at.is_some());
        assert!(page.next_page.is_none());
    }

    #[test]
    fn a_listing_pages_in_a_stable_order() {
        let dir = Scratch::new();
        for id in ["c3", "a1", "b2"] {
            write(dir.path(), "-work-jam", id, &[user("u", None, json!("hi"))]);
        }
        let first = list(dir.path(), &[], None, 2).unwrap();
        let ids: Vec<_> = first.items.iter().map(|i| i.native_id.as_str()).collect();
        assert_eq!(ids, ["a1", "b2"]);
        let rest = list(dir.path(), &[], first.next_page.as_deref(), 2).unwrap();
        assert_eq!(rest.items[0].native_id, "c3");
        // Without a title, the first prompt names it, as in Claude Code.
        assert_eq!(rest.items[0].title.as_deref(), Some("hi"));
        assert!(rest.next_page.is_none());
    }

    #[test]
    fn a_folder_hint_reads_only_the_folders_that_may_hold_it() {
        let dir = Scratch::new();
        write(
            dir.path(),
            "C--work-caf--repo",
            "a1",
            &[user("u1", None, json!("hi"))],
        );
        write(
            dir.path(),
            "C--work-other",
            "b2",
            &[user("u2", None, json!("hi"))],
        );
        let wanted = [r"C:\work\café repo".to_owned()];
        let page = list(dir.path(), &wanted, None, 10).unwrap();
        let ids: Vec<_> = page.items.iter().map(|i| i.native_id.as_str()).collect();
        assert_eq!(ids, ["a1"]);
        assert!(may_hold(&"x".repeat(200), &wanted));
        assert!(may_hold("anything", &[]));
    }

    #[test]
    fn a_read_keeps_the_current_branch_and_joins_each_reply() {
        let entries = vec![
            user(
                "u1",
                None,
                json!([{"type": "text", "text": "List the files"}]),
            ),
            assistant(
                "r1",
                "u1",
                json!([{"type": "thinking", "thinking": "Looking"}]),
            ),
            assistant(
                "r2",
                "r1",
                json!([{"type": "tool_use", "id": "t1", "name": "Bash", "input": {"command": "ls"}}]),
            ),
            user(
                "u2",
                Some("r2"),
                json!([{"type": "tool_result", "tool_use_id": "t1", "content": "a.txt"}]),
            ),
            assistant("r3", "u2", json!([{"type": "text", "text": "One file."}])),
            // An abandoned branch: the reader edited their next message.
            user("u3", Some("r3"), json!("Delete it")),
            user("u4", Some("r3"), json!("Keep it")),
            json!({"type": "user", "uuid": "m1", "parentUuid": "u4", "isMeta": true,
                   "message": {"content": "<local-command-caveat>"}}),
            assistant("r4", "u4", json!([{"type": "text", "text": "Kept."}])),
            // A background task finishing: Claude Code's turn, not the reader's.
            json!({"type": "user", "uuid": "n1", "parentUuid": "r4", "promptSource": "system",
                   "message": {"content": "<task-notification>
<result>a &amp;&amp; b</result>"}}),
            json!({"type": "user", "uuid": "n2", "parentUuid": "n1",
                   "message": {"content": "<task-notification>done</task-notification>"}}),
            json!({"type": "assistant", "uuid": "s1", "parentUuid": "n2", "isSidechain": true,
                   "message": {"content": [{"type": "text", "text": "sub-agent"}]}}),
        ];
        let out = messages(&entries);
        let ids: Vec<_> = out.iter().map(|m| m.source_id.as_str()).collect();
        assert_eq!(ids, ["u1", "r1", "u4", "r4"]);
        assert_eq!(out[1].role, "assistant");
        let MessageBlock::Tool {
            title,
            status,
            detail,
            ..
        } = &out[1].blocks[1]
        else {
            panic!("a tool block");
        };
        assert_eq!(
            (title.as_str(), status.as_str(), detail.as_str()),
            ("ls", "completed", "a.txt")
        );
        assert_eq!(
            out[1].blocks[2],
            MessageBlock::Text {
                text: "One file.".into()
            }
        );
    }

    #[test]
    fn a_read_follows_a_compaction_back_to_the_start() {
        let entries = vec![
            user("u1", None, json!("Start")),
            assistant("r1", "u1", json!([{"type": "text", "text": "Started."}])),
            json!({"type": "system", "subtype": "compact_boundary", "uuid": "c1",
                   "parentUuid": null, "logicalParentUuid": "r1"}),
            json!({"type": "user", "uuid": "cs", "parentUuid": "c1", "isCompactSummary": true,
                   "message": {"content": "Summary of the conversation"}}),
            user("u2", Some("cs"), json!("Continue")),
        ];
        let ids: Vec<_> = messages(&entries)
            .into_iter()
            .map(|m| m.source_id)
            .collect();
        assert_eq!(ids, ["u1", "r1", "u2"]);
    }

    #[test]
    fn reads_page_and_find_a_transcript_only_by_its_id() {
        let dir = Scratch::new();
        let path = write(
            dir.path(),
            "-work-jam",
            "a1",
            &[
                user("u1", None, json!("One")),
                assistant("r1", "u1", json!([{"type": "text", "text": "Two"}])),
                user("u2", Some("r1"), json!("Three")),
            ],
        );
        assert_eq!(transcript(dir.path(), "a1"), Some(path.clone()));
        assert_eq!(transcript(dir.path(), "../a1"), None);
        assert_eq!(transcript(dir.path(), "missing"), None);
        let first = read(&path, None, 2).unwrap();
        assert_eq!(first.messages.len(), 2);
        let rest = read(&path, first.next_page.as_deref(), 2).unwrap();
        assert_eq!(rest.messages[0].source_id, "u2");
        assert!(rest.next_page.is_none());
    }
}
